'use strict';
// Claudible — render a saved session transcript into a SELF-CONTAINED, shareable HTML "replay" page.
// Pure function, no IO. messages = [{role:'you'|'claude', text}]. The messages are embedded as JSON and
// the DOM is built client-side with textContent (so transcript text can never inject HTML); only the few
// metadata fields placed directly into markup are escaped here.
function escapeText(s) {
  return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
// Embed a value as a JS literal safely: neutralize </script> and the two JS-breaking line separators (U+2028/U+2029).
function jsonLiteral(v) {
  return JSON.stringify(v).replace(/</g, '\\u003c').replace(/[\u2028\u2029]/g, function(c){ return '\\u' + c.charCodeAt(0).toString(16); });
}
function renderReplayHtml({ title, workspace, date, messages } = {}) {
  const meta = { title: title || 'Claude session', workspace: workspace || '', date: date || '' };
  const msgs = Array.isArray(messages) ? messages : [];
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${escapeText(meta.title)} · Claudible replay</title>
<style>
  :root{--bg:#070809;--panel:#0d0f12;--ink:#e7eaef;--dim:#9097a1;--faint:#565c66;--hair:#2b2f37;--accent:#6aa6e0;--you:#17202c;--code:#0a0b0d}
  *{box-sizing:border-box}
  html,body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
  .wrap{max-width:840px;margin:0 auto;padding:0 18px 80px}
  header{padding:34px 0 18px;border-bottom:1px solid var(--hair);margin-bottom:22px}
  header .ttl{font-size:21px;font-weight:650;line-height:1.3;word-break:break-word}
  header .sub{margin-top:8px;font-size:12px;color:var(--faint);display:flex;gap:10px;flex-wrap:wrap;align-items:center}
  header .sub .chip{padding:3px 8px;border:1px solid var(--hair);border-radius:999px;color:var(--dim)}
  .bar{position:sticky;top:0;z-index:5;display:flex;align-items:center;gap:12px;padding:12px 0;margin-bottom:14px;
    background:linear-gradient(180deg,var(--bg) 70%,rgba(7,8,9,0));backdrop-filter:blur(2px)}
  .bar button{font:inherit;font-size:12.5px;color:var(--ink);background:var(--panel);border:1px solid var(--hair);
    border-radius:9px;padding:7px 14px;cursor:pointer}
  .bar button:hover{border-color:rgba(255,255,255,.25)}
  .bar .prog{flex:1;height:5px;border-radius:3px;background:#15171c;overflow:hidden}
  .bar .prog>i{display:block;height:100%;width:0;background:var(--accent);transition:width .25s}
  .bar .count{font-size:11px;color:var(--faint);font-variant-numeric:tabular-nums;min-width:62px;text-align:right}
  .msg{margin:0 0 14px;max-width:88%;padding:12px 15px;border-radius:14px;white-space:pre-wrap;word-break:break-word;
    opacity:0;transform:translateY(6px);transition:opacity .3s,transform .3s}
  .msg.show{opacity:1;transform:none}
  .msg.you{margin-left:auto;background:var(--you);border:1px solid #243243}
  .msg.claude{margin-right:auto;background:var(--panel);border:1px solid var(--hair)}
  .msg .who{display:block;font-size:9px;letter-spacing:.13em;text-transform:uppercase;color:var(--faint);margin-bottom:7px}
  .msg pre{margin:9px 0;padding:11px 13px;background:var(--code);border:1px solid var(--hair);border-radius:9px;
    overflow:auto;font:12.5px/1.5 ui-monospace,"SF Mono",Consolas,monospace;color:#cdd4dd;white-space:pre}
  footer{margin-top:34px;padding-top:18px;border-top:1px solid var(--hair);font-size:11.5px;color:var(--faint);text-align:center}
  footer a{color:var(--dim);text-decoration:none}
</style>
</head><body>
<div class="wrap">
  <header>
    <div class="ttl">${escapeText(meta.title)}</div>
    <div class="sub">
      ${meta.workspace ? '<span class="chip">' + escapeText(meta.workspace) + '</span>' : ''}
      ${meta.date ? '<span>' + escapeText(meta.date) + '</span>' : ''}
      <span>· ${msgs.length} message${msgs.length === 1 ? '' : 's'}</span>
    </div>
  </header>
  <div class="bar">
    <button id="play">▶ Replay</button>
    <button id="all">Show all</button>
    <div class="prog"><i id="fill"></i></div>
    <span class="count" id="count">0 / ${msgs.length}</span>
  </div>
  <main id="log"></main>
  <footer>Generated by <a href="https://github.com/synthetiks/claudible" target="_blank" rel="noopener">Claudible</a> — a collaborative cockpit for Claude Code</footer>
</div>
<script>
const MSGS = ${jsonLiteral(msgs)};
const log = document.getElementById('log'), fill = document.getElementById('fill'), count = document.getElementById('count');
// Build each message with textContent only (no HTML from transcript text). Fenced \`\`\` blocks become <pre>.
function build(m){
  const d = document.createElement('div'); d.className = 'msg ' + (m.role === 'you' ? 'you' : 'claude');
  const who = document.createElement('span'); who.className = 'who'; who.textContent = m.role === 'you' ? 'you' : 'claude'; d.appendChild(who);
  const parts = String(m.text || '').split(/\`\`\`/);
  parts.forEach(function(p, i){
    if (i % 2 === 1){ var pre = document.createElement('pre'); pre.textContent = p.replace(/^[^\\n]*\\n/, ''); d.appendChild(pre); }
    else if (p){ var span = document.createElement('div'); span.textContent = p; d.appendChild(span); }
  });
  return d;
}
const nodes = MSGS.map(function(m){ var n = build(m); log.appendChild(n); return n; });
let shown = 0, timer = null;
function setShown(n){
  shown = Math.max(0, Math.min(MSGS.length, n));
  nodes.forEach(function(node, i){ node.classList.toggle('show', i < shown); });
  fill.style.width = (MSGS.length ? (shown / MSGS.length * 100) : 0) + '%';
  count.textContent = shown + ' / ' + MSGS.length;
}
function showAll(){ if (timer){ clearInterval(timer); timer = null; } setShown(MSGS.length); }
function replay(){
  if (timer){ clearInterval(timer); timer = null; document.getElementById('play').textContent = '▶ Replay'; return; }
  if (shown >= MSGS.length) setShown(0);
  document.getElementById('play').textContent = '⏸ Pause';
  timer = setInterval(function(){
    if (shown >= MSGS.length){ clearInterval(timer); timer = null; document.getElementById('play').textContent = '▶ Replay'; return; }
    setShown(shown + 1);
    var last = nodes[shown - 1]; if (last) last.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, 650);
}
document.getElementById('play').addEventListener('click', replay);
document.getElementById('all').addEventListener('click', showAll);
showAll();   // default: full conversation visible; Replay re-plays it from the top
</script>
</body></html>`;
}
module.exports = { renderReplayHtml };
